spring:
  application:
    name: cloud-payment-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.11.24:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 47.111.11.24
  thymeleaf:
    cache: false
  rabbitmq:
    host: 47.111.11.24
    username: guest
    password: guest




logging:
  level:
    com.guigu.mapper: DEBUG


mybatis:
  mapper-locations: classpath:mapper/*Mapper
  type-aliases-package: com.guigu.springcloud.entities


